
name: Build OVA

description: "Builds an VMware OVA on a vSphere 'Builder' VM"

inputs:
  start_from:
    description: 'Step to start build FROM (inclusive)'
    required: true
    default: setup

runs:
  using: composite
  steps:
    - id: init
      name: Init
      shell: bash
      run: |
        echo "ran=!" >> $GITHUB_ENV
        echo "init — ${{ inputs.start_from }} — ${{ steps.id }}"
  
    - id: setup
      if: "setup" == inputs.start_from
      name: Setup
      shell: bash
      run: |
        echo "ran=setup" >> $GITHUB_ENV
        echo "setup"

    - id: start
      if: "start"==inputs.start_from || contains(env.ran,inputs.start_from)
      name: start
      shell: bash
      run: |
        echo "ran=start ${{env.ran}}" >> $GITHUB_ENV
        echo "start"
  
    - id: clean
      if: "clean"==inputs.start_from || contains(env.ran,inputs.start_from)
      name: clean
      shell: bash
      run: |
        echo "ran=clean ${{env.ran}}" >> $GITHUB_ENV
        echo "clean"
  
    - id: k8s
      if: "k8s"==inputs.start_from || contains(env.ran,inputs.start_from)
      name: k8s
      shell: bash
      run: |
        echo "ran=k8s ${{env.ran}}" >> $GITHUB_ENV
        echo "k8s"
  
    - id: tools
      if: "tools"==inputs.start_from || contains(env.ran,inputs.start_from)
      name: tools
      shell: bash
      run: |
        echo "ran=tools ${{env.ran}}" >> $GITHUB_ENV
        echo "tools"
  
    - id: iso
      if: "iso"==inputs.start_from || contains(env.ran,inputs.start_from)
      name: iso
      shell: bash
      run: |
        echo "ran=iso ${{env.ran}}" >> $GITHUB_ENV
        echo "iso"
  
    - id: upload
      if: "upload"==inputs.start_from || contains(env.ran,inputs.start_from)
      name: upload
      shell: bash
      run: |
        echo "ran=upload ${{env.ran}}" >> $GITHUB_ENV
        echo "upload"
  
    - id: install
      if: "install"==inputs.start_from || contains(env.ran,inputs.start_from)
      name: install
      shell: bash
      run: |
        echo "ran=install ${{env.ran}}" >> $GITHUB_ENV
        echo "install"
  
    - id: export
      if: "export"==inputs.start_from || contains(env.ran,inputs.start_from)
      name: export
      shell: bash
      run: |
        echo "ran=export ${{env.ran}}" >> $GITHUB_ENV
        echo "export"
  
