
name: 'Get Concurrency Key'

description: 'Sets concurrency_key as output'

inputs:
  vcenter_server:
    description: 'vCenter Server to run on'
    required: false
    default: 10.174.8.106

runs:
  using: "composite"
  steps:
    - name: "Generate environment vars file"
      env:
        concurrency_key: ova-build-${{ inputs.vcenter_server }}-${{ github.ref }}
      shell: bash
      run: |
        echo "Concurrency key: ${{ env.concurrency_key }}"

outputs:
  concurrency_key:
    description: 'Key by which to limit concurrency'
    value: ${{ env.concurrency_key }}
