
name: 'Set environment variables'

description: 'Configures environment variables for a workflow'

inputs:
  vcenter_server:
    description: "IP address or domain name for vCenter Server (must have a vcenter/<host>.json file in repo for this to work)"
    required: false
    default: 10.174.8.38
  vm_size:
    description: "Size of OVA to generate (mini, small, medium or large)"
    required: false
    default: mini
  vars_file:
    description: "File containing environment variables"
    required: false
    default: ./.github/vars/vars.env

runs:
  using: "composite"
  steps:
    - name: "Generate environment vars file"
      shell: bash
      run: |
        {
          echo "VCENTER_SERVER=${{ inputs.vcenter_server }}"
          echo "VM_SIZE=${{ inputs.vm_size }}"
          echo "VCENTER_USERNAME=foo@bar.baz"
          echo "VCENTER_PASSWORD=it-is-a-secret"
        } > ${{ inputs.vars_file }}
        cat ${{ inputs.vars_file }}

outputs:
  concurrency_key:
    description: 'Key by which to limit concurrency'
    value: ova-build-${{ inputs.vcenter_server }}-${{ github.ref }}
  vars_file:
    description: "Filepath of Environment Vars file"
    value: ${{ inputs.vars_file }}