
name: 'Set environment variables'

description: 'Configures environment variables for a workflow'

# See https://arinco.com.au/blog/github-actions-share-environment-variables-across-workflows/


inputs:
  vcenter_server:
    description: "IP address or domain name for vCenter Server (must have a vcenter/<host>.json file in repo for this to work)"
    required: false
    default: 10.174.8.38
  vm_size:
    description: "Size of OVA to generate (mini, small, medium or large)"
    required: false
    default: mini

runs:
  using: "composite"
  steps:
    - name: "Generate environment vars file"
      shell: bash
      env:
        vars_file: github/vars/vars.env
      run: |
        {
          echo "VCENTER_SERVER=${{ inputs.vcenter_server }}"
          echo "VM_SIZE=${{ inputs.vm_size }}"
          echo "VCENTER_USERNAME=foo@bar.baz"
          echo "VCENTER_PASSWORD=it-is-a-secret"
        } > ${{ env.vars_file }}
        sed "" ${{ env.vars_file }} >> $GITHUB_ENV

