
name: 'Set environment variables'

description: 'Configures environment variables for a workflow'

inputs:
  vcenter_server:
    description: "IP address or domain name for vCenter Server (must have a vcenter/<host>.json file in repo for this to work)"
    required: false
    default: 10.174.8.106
  vm_size:
    description: "Size of OVA to generate (mini, small, medium or large)"
    required: false
    default: small
  filepath:
    description: "File containing environment variables"
    required: false
    default: ./.github/vars/env.var

runs:
  using: "composite"
  steps:
    - name: "Generate environment vars file: ${{ github.event.inputs.filepath }}"
      shell: bash
      run: |
        {
          echo "VCENTER_SERVER='${{ github.event.inputs.vcenter_server }}'"
          echo "VM_SIZE='${{ inputs.vm_size }}'"
          echo "VCENTER_USERNAME=foo@bar.baz"
          echo "VCENTER_PASSWORD=it-is-a-secret"
        } > ${{ inputs.filepath }}
        sed "" ${{ github.event.inputs.filepath }} >> $GITHUB_ENV
        cat $GITHUB_ENV

outputs:
  filepath:
    description: 'Filepath of Environment Vars file'
    value: ${{ github.event.inputs.filepath }}
  concurrency_key:
    description: 'Key by which to limit concurrency'
    value: ova-build-${{ github.event.inputs.vcenter_server }}-${{ github.ref }}
