
name: Build OVA

on:
  workflow_dispatch:
    inputs:
      vcenter_server:
        type: choice
        description: 'vCenter Server to run OVA build on'
        required: true
        default: 10.174.8.106
        options:
          - 10.174.8.106
          - 10.174.8.38

      vm_size:
        type: choice
        description: 'Size of OVA to build'
        required: true
        default: small
        options:
          - mini
          - small
          - medium
          - large

      start_from:
        type: choice
        description: 'Step to start build FROM (inclusive)'
        required: false
        default: k8s
        options:
          - setup
          - start
          - clean
          - k8s
          - tools
          - iso
          - upload
          - install
          - export

jobs:
  call-workflow-passing-data:
    uses: ./.github/workflows/build-ova.yaml
    with:
      vcenter_server: ${{ github.event.inputs.vcenter_server }}
      vm_size: ${{ github.event.inputs.vm_size }}
      start_from: ${{ github.event.inputs.start_from }}


#  build:
#    runs-on: ubuntu-latest
#    needs: init
#    concurrency:
#      group: ${{ needs.init.outputs.concurrency_key }}"
#      cancel-in-progress: true
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v2
#      - name: Set Environment Variables
#        uses: ./.github/actions/set-vars
#        with:
#          vcenter_server: ${{ github.event.inputs.vcenter_server }}
#          vm_size: ${{ github.event.inputs.vm_size }}
#        id: set_vars
#      - name: Show Vars
#        run: |
#          echo "CONCURRENCY_KEY:  ${{ needs.init.outputs.concurrency_key }}"
#          echo "VCENTER_SERVER:   ${{ env.VCENTER_SERVER }}"
#          echo "VCENTER_USERNAME: ${{ env.VCENTER_USERNAME }}"
#          echo "VCENTER_PASSWORD: ${{ env.VCENTER_PASSWORD }}"
#          echo "VM_SIZE:          ${{ env.VM_SIZE }}"
#
#

