
name: Test Set Vars

on:
  workflow_dispatch:
    inputs:
      vcenter_server:
        type: choice
        description: 'vCenter Server to run OVA build on'
        required: true
        default: 10.174.8.106
        options:
          - 10.174.8.106
          - 10.174.8.38

      vm_size:
        type: choice
        description: 'Size of OVA to build'
        required: true
        default: small
        options:
          - mini
          - small
          - medium
          - large

      build_from:
        type: choice
        description: 'Make target to build FROM (inclusive)'
        required: false
        default: from-setup
        options:
          - from-setup
          - from-start
          - from-clean
          - from-k8s
          - from-tools
          - from-iso
          - from-upload
          - from-install
          - from-export

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - id: get_key
        name: Get Key
        uses: ./.github/actions/concurrency-key
        with:
          vcenter_server: ${{ github.event.inputs.vcenter_server }}
      - name: Show Key
        run: |
          echo "Concurrency Key: ${{ steps.get_key.outputs.concurrency_key }}"
    outputs:
      concurrency_key: ${{ steps.get_key.outputs.concurrency_key }}

  build:
    runs-on: ubuntu-latest
    needs: init
    concurrency:
      group: ${{ needs.init.outputs.concurrency_key }}"
      cancel-in-progress: true
    steps:
      - id: set_vars
        name: Set Environment Variables
        uses: ./.github/actions/set-vars
        with:
          vcenter_server: ${{ github.event.inputs.vcenter_server }}
          vm_size: ${{ github.event.inputs.vm_size }}
      - name: Show Vars
        run: |
          echo "CONCURRENCY_KEY:  ${{ needs.init.outputs.concurrency_key }}"
          echo "VCENTER_SERVER:   ${{ env.VCENTER_SERVER }}"
          echo "VCENTER_USERNAME: ${{ env.VCENTER_USERNAME }}"
          echo "VCENTER_PASSWORD: ${{ env.VCENTER_PASSWORD }}"
          echo "VM_SIZE:          ${{ env.VM_SIZE }}"



