
name: Test Set Vars

on:
  workflow_dispatch:
    inputs:
      vcenter_server:
        type: choice
        description: 'vCenter Server to run OVA build on'
        required: true
        default: 10.174.8.106
        options:
          - 10.174.8.106
          - 10.174.8.38

      vm_size:
        type: choice
        description: 'Size of OVA to build'
        required: true
        default: small
        options:
          - mini
          - small
          - medium
          - large

      start_from:
        type: choice
        description: 'Step to start build FROM (inclusive)'
        required: false
        default: setup
        options:
          - setup
          - start
          - clean
          - k8s
          - tools
          - iso
          - upload
          - install
          - export

jobs:
  init:
    runs-on: ubuntu-latest
    outputs:
      concurrency_key: ${{ steps.get_key.outputs.concurrency_key }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        if: success()
      - name: Get Key
        id: get_key
        uses: ./.github/actions/concurrency-key
        with:
          vcenter_server: ${{ github.event.inputs.vcenter_server }}


  build:
    runs-on: ubuntu-latest
    needs: init
    env:
      start_from: ${{ github.event.inputs.start_from }}
    steps:
      - id: setup
        #if: github.action == ${{ env.start_from }}
        env:
          step_no: 1
        name: Setup
        run: echo "setup — ${{ env.step_no }}"

      - id: start
        #if: github.action == ${{ env.start_from }}
        env:
          step_no: 2
        name: start
        run: echo "start — ${{ env.step_no }}"

      - id: clean
        #if: github.action == ${{ env.start_from }}
        env:
          step_no: 3
        name: clean
        run: echo "clean — ${{ env.step_no }}"

      - id: k8s
        #if: github.action == ${{ env.start_from }}
        env:
          step_no: 4
        name: k8s
        run: echo "k8s — ${{ env.step_no }}"

      - id: tools
        #if: github.action == ${{ env.start_from }}
        env:
          step_no: 5
        name: tools
        run: echo "tools — ${{ env.step_no }}"

      - id: iso
        #if: github.action == ${{ env.start_from }}
        env:
          step_no: 6
        name: iso
        run: echo "iso — ${{ env.step_no }}"

      - id: upload
        #if: github.action == ${{ env.start_from }}
        env:
          step_no: 7
        name: upload
        run: echo "upload — ${{ env.step_no }}"

      - id: install
        #if: github.action == ${{ env.start_from }}
        env:
          step_no: 8
        name: install
        run: echo "install — ${{ env.step_no }}"

      - id: export
        #if: github.action == ${{ env.start_from }}
        env:
          step_no: 9
        name: export
        run: echo "export — ${{ env.step_no }}"


#  build:
#    runs-on: ubuntu-latest
#    needs: init
#    concurrency:
#      group: ${{ needs.init.outputs.concurrency_key }}"
#      cancel-in-progress: true
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v2
#      - name: Set Environment Variables
#        uses: ./.github/actions/set-vars
#        with:
#          vcenter_server: ${{ github.event.inputs.vcenter_server }}
#          vm_size: ${{ github.event.inputs.vm_size }}
#        id: set_vars
#      - name: Show Vars
#        run: |
#          echo "CONCURRENCY_KEY:  ${{ needs.init.outputs.concurrency_key }}"
#          echo "VCENTER_SERVER:   ${{ env.VCENTER_SERVER }}"
#          echo "VCENTER_USERNAME: ${{ env.VCENTER_USERNAME }}"
#          echo "VCENTER_PASSWORD: ${{ env.VCENTER_PASSWORD }}"
#          echo "VM_SIZE:          ${{ env.VM_SIZE }}"
#
#

