
name: Test Set Vars

on:
  workflow_dispatch:
    inputs:
      vcenter_server:
        type: choice
        description: 'vCenter Server to run OVA build on'
        required: true
        default: 10.174.8.106
        options:
          - 10.174.8.106
          - 10.174.8.38

      vm_size:
        type: choice
        description: 'Size of OVA to build'
        required: true
        default: small
        options:
          - mini
          - small
          - medium
          - large

      build_from:
        type: choice
        description: 'Make target to build FROM (inclusive)'
        required: false
        default: from-setup
        options:
          - from-setup
          - from-start
          - from-clean
          - from-k8s
          - from-tools
          - from-iso
          - from-upload
          - from-install
          - from-export


jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - id: set_vars
        name: Set Environment Variables
        uses: ./.github/actions/set-vars
        with:
          vcenter_server: ${{ inputs.vcenter_server }}
          vm_size: ${{ inputs.vm_size }}
    outputs:
      concurrency_key: ${{ steps.set_vars.outputs.concurrency_key }}

  gatekeeper:
    runs-on: ubuntu-latest
    needs: init
    concurrency: ${{ needs.init.outputs.concurrency_key }}
    steps:
      - name: Announce intent
        run: echo 'One at a time'

  show:
    runs-on: ubuntu-latest
    needs: gatekeeper
    steps:
      - name: Show Vars
        run: |
          echo "CONCURRENCY_KEY: ${{ needs.init.outputs.concurrency_key }}"
          env


