
name: Build OVA

on:
  workflow_dispatch:
    inputs:
      start_from:
        type: choice
        description: 'Step to start build FROM (inclusive)'
        required: false
        default: setup
        options:
          - setup
          - start
          - clean
          - k8s
          - tools
          - iso
          - upload
          - install
          - export

env:
  start_from: ${{ github.event.inputs.start_from }}
  ran: "!"

jobs:
  build:
    name: "Build OVA"
    runs-on: ubuntu-latest
    steps:

        - id: setup
          if: env.start_from == 'setup'
          name: Setup
          shell: bash
          run: |
            echo "ran=setup" >> $GITHUB_ENV
            echo "setup"

        - id: start
          if: env.start_from == 'start' || contains(env.ran,env.start_from)
          name: start
          shell: bash
          run: |
            echo "ran=start ${{env.ran}}" >> $GITHUB_ENV
            echo "start"

        - id: clean
          if: env.start_from == 'clean' || contains(env.ran,env.start_from)
          name: clean
          shell: bash
          run: |
            echo "ran=clean ${{env.ran}}" >> $GITHUB_ENV
            echo "clean"

        - id: k8s
          if: env.start_from == 'k8s' || contains(env.ran,env.start_from)
          name: k8s
          shell: bash
          run: |
            echo "ran=k8s ${{env.ran}}" >> $GITHUB_ENV
            echo "k8s"

        - id: tools
          if: env.start_from == 'tools' || contains(env.ran,env.start_from)
          name: tools
          shell: bash
          run: |
            echo "ran=tools ${{env.ran}}" >> $GITHUB_ENV
            echo "tools"

        - id: iso
          if: env.start_from == 'iso' || contains(env.ran,env.start_from)
          name: iso
          shell: bash
          run: |
            echo "ran=iso ${{env.ran}}" >> $GITHUB_ENV
            echo "iso"

        - id: upload
          if: env.start_from == 'upload' || contains(env.ran,env.start_from)
          name: upload
          shell: bash
          run: |
            echo "ran=upload ${{env.ran}}" >> $GITHUB_ENV
            echo "upload"

        - id: install
          if: env.start_from == 'install' || contains(env.ran,env.start_from)
          name: install
          shell: bash
          run: |
            echo "ran=install ${{env.ran}}" >> $GITHUB_ENV
            echo "install"

        - id: export
          if: env.start_from == 'export' || contains(env.ran,env.start_from)
          name: export
          shell: bash
          run: |
            echo "ran=export ${{env.ran}}" >> $GITHUB_ENV
            echo "export"
  
